name 'app'
maintainer 'Engine Yard'

depends 'deploy-keys'
depends 'app-logs'
depends 'unicorn'
depends 'passenger5'
depends 'puma'
depends 'monit'
depends 'env_vars'
depends 'cdn_distribution'
depends 'db_admin_tools'
depends 'mysql'
depends 'postgresql'
depends 'nginx'
depends 'ruby'
depends 'ey-db-libs'

=begin
depends 'ey-lib'
depends 'deploy'
depends 'db_admin_tools'
depends 'deploy-keys'
depends 'ey-cron'
depends 'postgresql'
depends 'mysql'
depends 'app-logs'
depends 'deploy'
depends 'env_vars'
depends 'cdn_distribution'
=end
