name 'ey-base'
maintainer 'Engine Yard'
maintainer_email 'support@engineyard.com'
version '1.0'
source_url 'https://engineyard.com'
issues_url 'https://support.engineyard.com'

depends 'ec2'
depends 'ephemeraldisk'
depends 'ey-dynamic'
depends 'ruby'
depends 'app'
depends 'nginx'
depends 'sudo'
depends 'db_master'
depends 'db_replica'
depends 'ssh_keys'
depends 'nodejs'
depends 'ey-env'
depends 'framework_env'
depends 'reboot'
depends 'ey-cron'
depends 'ey-backup'
depends 'collectd'
depends 'util'
depends 'prompt'
depends 'efs'

# custom recipes
depends 'redis'
depends 'memcached'
depends 'sidekiq'
