name 'ey-core'
maintainer 'Engine Yard'

depends 'logrotate'
depends 'run-one'
depends 'sysctl'
depends 'ey-instance-api'
depends 'ntp'
depends 'openssl'
depends 'security_updates'
depends 'ey-hosts'
depends 'timezones'
depends 'syslog-ng'
depends 'prechef'

=begin
depends 'ey-lib'
depends 'ntp'
depends 'emerge'
depends 'ephemeraldisk'
depends 'ey-dynamic'
depends 'ey-instance-api'
depends 'ey-monitor'
depends 'lockrun'
depends 'logrotate'
depends 'openssl'
depends 'prechef'
depends 'security_updates'
depends 'sysctl'
depends 'sysklogd'
depends 'timezones'
depends 'ey-hosts'
=end
