name 'util'
maintainer 'Engine Yard'

depends 'ey-lib'
depends 'app'
depends 'db_admin_tools'
depends 'deploy-keys'
depends 'ey-cron'
depends 'postgresql'
depends 'mysql'
depends 'app-logs'
depends 'ey-db-libs'
